// Auto-generated by parallel_unsplash_photos_search
// Do not edit manually

export const IMAGES = {
  MISSION_CONTROL_1: "https://images.unsplash.com/photo-1484253292651-6e940b0a0e26?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHwxfHxkYXJrJTIwbWlzc2lvbiUyMGNvbnRyb2wlMjBpbnRlbGxpZ2VuY2UlMjBkYXRhJTIwY2VudGVyJTIwb3BlcmF0aW9uc3xlbnwwfDB8fGJsYWNrfDE3Nzg0NDAxNDd8MA&ixlib=rb-4.1.0&q=80&w=1080",
  MISSION_CONTROL_2: "https://images.unsplash.com/photo-1507333199169-84fd735371fb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHwzfHxkYXJrJTIwbWlzc2lvbiUyMGNvbnRyb2wlMjBpbnRlbGxpZ2VuY2UlMjBkYXRhJTIwY2VudGVyJTIwb3BlcmF0aW9uc3xlbnwwfDB8fGJsYWNrfDE3Nzg0NDAxNDd8MA&ixlib=rb-4.1.0&q=80&w=1080",
  MISSION_CONTROL_3: "https://images.unsplash.com/photo-1597138768744-9f97be8cdd64?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTk0NTh8MHwxfHNlYXJjaHwyfHxkYXJrJTIwbWlzc2lvbiUyMGNvbnRyb2wlMjBpbnRlbGxpZ2VuY2UlMjBkYXRhJTIwY2VudGVyJTIwb3BlcmF0aW9uc3xlbnwwfDB8fGJsYWNrfDE3Nzg0NDAxNDd8MA&ixlib=rb-4.1.0&q=80&w=1080",
  UNIVERSITY_LAB_1: "https://images.unsplash.com/photo-1572884267966-02340ebc90ac?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHw4fHx1bml2ZXJzaXR5JTIwcmVzZWFyY2glMjBsYWJvcmF0b3J5JTIwdGVjaG5vbG9neSUyMGlubm92YXRpb258ZW58MHwwfHx8MTc3ODQ0MDE0Nnww&ixlib=rb-4.1.0&q=80&w=1080",
  UNIVERSITY_LAB_2: "https://images.unsplash.com/photo-1602052577122-f73b9710adba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHw2fHx1bml2ZXJzaXR5JTIwcmVzZWFyY2glMjBsYWJvcmF0b3J5JTIwdGVjaG5vbG9neSUyMGlubm92YXRpb258ZW58MHwwfHx8MTc3ODQ0MDE0Nnww&ixlib=rb-4.1.0&q=80&w=1080",
  UNIVERSITY_LAB_3: "https://images.unsplash.com/photo-1562411053-1d8bdfe771c1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHw3fHx1bml2ZXJzaXR5JTIwcmVzZWFyY2glMjBsYWJvcmF0b3J5JTIwdGVjaG5vbG9neSUyMGlubm92YXRpb258ZW58MHwwfHx8MTc3ODQ0MDE0Nnww&ixlib=rb-4.1.0&q=80&w=1080",
  UNIVERSITY_LAB_4: "https://images.unsplash.com/photo-1602052294200-a8b75e03adfe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHw1fHx1bml2ZXJzaXR5JTIwcmVzZWFyY2glMjBsYWJvcmF0b3J5JTIwdGVjaG5vbG9neSUyMGlubm92YXRpb258ZW58MHwwfHx8MTc3ODQ0MDE0Nnww&ixlib=rb-4.1.0&q=80&w=1080",
  UNIVERSITY_LAB_5: "https://images.unsplash.com/photo-1705727210721-961cc64a6895?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHw0fHx1bml2ZXJzaXR5JTIwcmVzZWFyY2glMjBsYWJvcmF0b3J5JTIwdGVjaG5vbG9neSUyMGlubm92YXRpb258ZW58MHwwfHx8MTc3ODQ0MDE0Nnww&ixlib=rb-4.1.0&q=80&w=1080",
  UNIVERSITY_LAB_6: "https://images.unsplash.com/photo-1766297247924-6638d54e7c89?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHwxfHx1bml2ZXJzaXR5JTIwcmVzZWFyY2glMjBsYWJvcmF0b3J5JTIwdGVjaG5vbG9neSUyMGlubm92YXRpb258ZW58MHwwfHx8MTc3ODQ0MDE0Nnww&ixlib=rb-4.1.0&q=80&w=1080",
  UNIVERSITY_LAB_7: "https://images.unsplash.com/photo-1758685848587-7bc7487b6e85?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHwyfHx1bml2ZXJzaXR5JTIwcmVzZWFyY2glMjBsYWJvcmF0b3J5JTIwdGVjaG5vbG9neSUyMGlubm92YXRpb258ZW58MHwwfHx8MTc3ODQ0MDE0Nnww&ixlib=rb-4.1.0&q=80&w=1080",
  UNIVERSITY_LAB_8: "https://images.unsplash.com/photo-1766297248160-87aca6fa59ef?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NDU5NTF8MHwxfHNlYXJjaHwzfHx1bml2ZXJzaXR5JTIwcmVzZWFyY2glMjBsYWJvcmF0b3J5JTIwdGVjaG5vbG9neSUyMGlubm92YXRpb258ZW58MHwwfHx8MTc3ODQ0MDE0Nnww&ixlib=rb-4.1.0&q=80&w=1080",
} as const;

export type ImageKey = keyof typeof IMAGES;
